name: Label-issues
on: 
  issues:
    types:
      -repoened
      -opened
jobs:
  label-issues:
     runs-on: ubuntu-latest
     permissions:
        issues: write
  steps:
    name: label issues
    uses: andymckay/simple-issue-labler./.github/workflows/labeler@1.0.4
    with:
      add labels: "triage"
      repos-token: ${{secrets.GITHUB_TOKEN}}
